[build]
  publish = "dist"
  command = "pnpm install --no-frozen-lockfile && pnpm run build"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "10.4.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

